# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 864)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 1041, 801))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.trainerLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.trainerLayout.setContentsMargins(0, 0, 0, 0)
        self.trainerLayout.setObjectName("trainerLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.verticalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Welcome = QtWidgets.QWidget()
        self.Welcome.setObjectName("Welcome")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.Welcome)
        self.textBrowser.setGeometry(QtCore.QRect(260, 90, 511, 261))
        self.textBrowser.setObjectName("textBrowser")
        self.stackedWidget.addWidget(self.Welcome)
        self.newTrainer = QtWidgets.QWidget()
        self.newTrainer.setObjectName("newTrainer")
        self.labelCreateTrainerStatus = QtWidgets.QLabel(parent=self.newTrainer)
        self.labelCreateTrainerStatus.setGeometry(QtCore.QRect(110, 80, 181, 171))
        self.labelCreateTrainerStatus.setText("")
        self.labelCreateTrainerStatus.setObjectName("labelCreateTrainerStatus")
        self.textEdit = QtWidgets.QTextEdit(parent=self.newTrainer)
        self.textEdit.setGeometry(QtCore.QRect(420, 20, 581, 391))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.newTrainer)
        self.formLayoutWidget.setGeometry(QtCore.QRect(80, 30, 231, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_13 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_13)
        self.inputTrainerName = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.inputTrainerName.setObjectName("inputTrainerName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.inputTrainerName)
        self.btnCreateTrainer = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.btnCreateTrainer.setObjectName("btnCreateTrainer")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnCreateTrainer)
        self.stackedWidget.addWidget(self.newTrainer)
        self.openedProject = QtWidgets.QWidget()
        self.openedProject.setObjectName("openedProject")
        self.textProjectInfo = QtWidgets.QTextBrowser(parent=self.openedProject)
        self.textProjectInfo.setGeometry(QtCore.QRect(210, 30, 621, 381))
        self.textProjectInfo.setObjectName("textProjectInfo")
        self.stackedWidget.addWidget(self.openedProject)
        self.TrainerEditor = QtWidgets.QWidget()
        self.TrainerEditor.setObjectName("TrainerEditor")
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.TrainerEditor)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 201, 628))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.comboTrainerDropdown = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboTrainerDropdown.setEditable(False)
        self.comboTrainerDropdown.setObjectName("comboTrainerDropdown")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboTrainerDropdown)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_2)
        self.lineTrainerName = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.lineTrainerName.setObjectName("lineTrainerName")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineTrainerName)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_3)
        self.comboTrainerClass = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboTrainerClass.setObjectName("comboTrainerClass")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboTrainerClass)
        self.label_5 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_5)
        self.comboTrainerGender = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboTrainerGender.setObjectName("comboTrainerGender")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboTrainerGender)
        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_4)
        self.comboTrainerPic = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboTrainerPic.setObjectName("comboTrainerPic")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboTrainerPic)
        self.label_6 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_6)
        self.comboTrainerMusic = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboTrainerMusic.setObjectName("comboTrainerMusic")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboTrainerMusic)
        self.checkDoubleBattle = QtWidgets.QCheckBox(parent=self.formLayoutWidget_2)
        self.checkDoubleBattle.setObjectName("checkDoubleBattle")
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkDoubleBattle)
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label)
        self.label_7 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_7)
        self.comboAIFlags = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboAIFlags.setObjectName("comboAIFlags")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboAIFlags)
        self.comboTeamSize = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboTeamSize.setObjectName("comboTeamSize")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboTeamSize)
        self.label_8 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(20, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_9)
        self.comboTrainerItem1 = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboTrainerItem1.setObjectName("comboTrainerItem1")
        self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboTrainerItem1)
        self.label_11 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_11)
        self.label_10 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_10)
        self.comboTrainerItem2 = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboTrainerItem2.setObjectName("comboTrainerItem2")
        self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboTrainerItem2)
        self.comboTrainerItem3 = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboTrainerItem3.setObjectName("comboTrainerItem3")
        self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboTrainerItem3)
        self.comboMugshot = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.comboMugshot.setObjectName("comboMugshot")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboMugshot)
        self.label_12 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_12)
        self.lblTrainerPic = QtWidgets.QLabel(parent=self.TrainerEditor)
        self.lblTrainerPic.setGeometry(QtCore.QRect(250, 90, 192, 192))
        self.lblTrainerPic.setText("")
        self.lblTrainerPic.setScaledContents(True)
        self.lblTrainerPic.setObjectName("lblTrainerPic")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.TrainerEditor)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(470, 240, 561, 551))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.partyLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.partyLayout.setContentsMargins(0, 0, 0, 0)
        self.partyLayout.setObjectName("partyLayout")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.TrainerEditor)
        self.textEdit_2.setGeometry(QtCore.QRect(470, 10, 551, 221))
        self.textEdit_2.setObjectName("textEdit_2")
        self.stackedWidget.addWidget(self.TrainerEditor)
        self.pageMapScripts = QtWidgets.QWidget()
        self.pageMapScripts.setObjectName("pageMapScripts")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.pageMapScripts)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 481, 541))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layoutEventScript = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layoutEventScript.setContentsMargins(0, 0, 0, 0)
        self.layoutEventScript.setObjectName("layoutEventScript")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.pageMapScripts)
        self.textEdit_3.setGeometry(QtCore.QRect(520, 20, 511, 631))
        self.textEdit_3.setObjectName("textEdit_3")
        self.stackedWidget.addWidget(self.pageMapScripts)
        self.pageImportTrainerPics = QtWidgets.QWidget()
        self.pageImportTrainerPics.setObjectName("pageImportTrainerPics")
        self.importButton = QtWidgets.QPushButton(parent=self.pageImportTrainerPics)
        self.importButton.setGeometry(QtCore.QRect(130, 30, 131, 24))
        self.importButton.setObjectName("importButton")
        self.debugLabel = QtWidgets.QLabel(parent=self.pageImportTrainerPics)
        self.debugLabel.setGeometry(QtCore.QRect(80, 70, 241, 20))
        self.debugLabel.setText("")
        self.debugLabel.setObjectName("debugLabel")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.pageImportTrainerPics)
        self.textBrowser_2.setGeometry(QtCore.QRect(420, 20, 561, 471))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.stackedWidget.addWidget(self.pageImportTrainerPics)
        self.pageImportOWSprite = QtWidgets.QWidget()
        self.pageImportOWSprite.setObjectName("pageImportOWSprite")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.pageImportOWSprite)
        self.textBrowser_3.setGeometry(QtCore.QRect(400, 20, 591, 401))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.importButton_OW = QtWidgets.QPushButton(parent=self.pageImportOWSprite)
        self.importButton_OW.setGeometry(QtCore.QRect(120, 30, 131, 24))
        self.importButton_OW.setObjectName("importButton_OW")
        self.labelImportOverworldStatus = QtWidgets.QLabel(parent=self.pageImportOWSprite)
        self.labelImportOverworldStatus.setGeometry(QtCore.QRect(80, 60, 211, 16))
        self.labelImportOverworldStatus.setText("")
        self.labelImportOverworldStatus.setObjectName("labelImportOverworldStatus")
        self.labelOverworldInfo = QtWidgets.QLabel(parent=self.pageImportOWSprite)
        self.labelOverworldInfo.setGeometry(QtCore.QRect(100, 140, 211, 16))
        self.labelOverworldInfo.setText("")
        self.labelOverworldInfo.setObjectName("labelOverworldInfo")
        self.stackedWidget.addWidget(self.pageImportOWSprite)
        self.trainerLayout.addWidget(self.stackedWidget)
        self.lblFolderPath = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFolderPath.setGeometry(QtCore.QRect(-440, 760, 469, 16))
        self.lblFolderPath.setObjectName("lblFolderPath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 22))
        self.menubar.setObjectName("menubar")
        self.menuTrainer_Editor = QtWidgets.QMenu(parent=self.menubar)
        self.menuTrainer_Editor.setObjectName("menuTrainer_Editor")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTrainerEditor = QtGui.QAction(parent=MainWindow)
        self.actionTrainerEditor.setObjectName("actionTrainerEditor")
        self.actionImportTrainerPics = QtGui.QAction(parent=MainWindow)
        self.actionImportTrainerPics.setObjectName("actionImportTrainerPics")
        self.actionImportOverworldSprites = QtGui.QAction(parent=MainWindow)
        self.actionImportOverworldSprites.setObjectName("actionImportOverworldSprites")
        self.actionMapScriptEditor_2 = QtGui.QAction(parent=MainWindow)
        self.actionMapScriptEditor_2.setObjectName("actionMapScriptEditor_2")
        self.actionGithub = QtGui.QAction(parent=MainWindow)
        self.actionGithub.setObjectName("actionGithub")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionRecent = QtGui.QAction(parent=MainWindow)
        self.actionRecent.setObjectName("actionRecent")
        self.actionNew = QtGui.QAction(parent=MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionactionOpenProjectFolder = QtGui.QAction(parent=MainWindow)
        self.actionactionOpenProjectFolder.setObjectName("actionactionOpenProjectFolder")
        self.actionOpenProjectFolder = QtGui.QAction(parent=MainWindow)
        self.actionOpenProjectFolder.setCheckable(False)
        self.actionOpenProjectFolder.setObjectName("actionOpenProjectFolder")
        self.actionOption1 = QtGui.QAction(parent=MainWindow)
        self.actionOption1.setObjectName("actionOption1")
        self.actionOption2 = QtGui.QAction(parent=MainWindow)
        self.actionOption2.setObjectName("actionOption2")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionRecentProjectss = QtGui.QAction(parent=MainWindow)
        self.actionRecentProjectss.setObjectName("actionRecentProjectss")
        self.actionNewTrainerPage = QtGui.QAction(parent=MainWindow)
        self.actionNewTrainerPage.setObjectName("actionNewTrainerPage")
        self.actionReloadProjectFolder = QtGui.QAction(parent=MainWindow)
        self.actionReloadProjectFolder.setObjectName("actionReloadProjectFolder")
        self.menuTrainer_Editor.addAction(self.actionOpenProjectFolder)
        self.menuTrainer_Editor.addAction(self.actionRecentProjectss)
        self.menuTrainer_Editor.addAction(self.actionReloadProjectFolder)
        self.menuTrainer_Editor.addSeparator()
        self.menuTrainer_Editor.addAction(self.actionTrainerEditor)
        self.menuTrainer_Editor.addAction(self.actionNewTrainerPage)
        self.menuTrainer_Editor.addSeparator()
        self.menuTrainer_Editor.addAction(self.actionMapScriptEditor_2)
        self.menuTrainer_Editor.addSeparator()
        self.menuTrainer_Editor.addAction(self.actionImportTrainerPics)
        self.menuTrainer_Editor.addAction(self.actionImportOverworldSprites)
        self.menuTrainer_Editor.addSeparator()
        self.menuTrainer_Editor.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionGithub)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuTrainer_Editor.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h1 style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:xx-large; font-weight:700;\">Welcome to PE Editor </span></h1>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This tool helps you edit trainer data for <span style=\" font-weight:700;\">pokeemerald-expansion</span> projects. </p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">📌 Important Information</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This editor is <span style=\" font-weight:700;\">only compatible</span> with <a href=\"https://github.com/rh-hideout/pokeemerald-expansion\"><span style=\" text-decoration: underline; color:#66ccff;\">pokeemerald-expansion</span></a>. </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It will not work correctly with the original <span style=\" font-family:\'Courier New\';\">pokeemerald</span> (vanilla). </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To create and export event scripts, your project must also include <a href=\"https://github.com/huderlem/poryscript\"><span style=\" text-decoration: underline; color:#66ccff;\">Poryscript</span></a>. </li></ul>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">🛠️ Recommended Tool</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">For inserting event scripts onto map objects, its highly recommend using <a href=\"https://github.com/huderlem/porymap\"><span style=\" text-decoration: underline; color:#66ccff;\">PoryMap</span></a>. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please make sure you\'ve selected the correct project folder using <span style=\" font-style:italic;\">File → Open Project Folder</span>. </p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">Add New Trainer </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use this form to create a new trainer in your project. The trainer will automatically be added to both <span style=\" font-family:\'Courier New\';\">opponents.h</span> and <span style=\" font-family:\'Courier New\';\">trainers.party</span>. </p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">✅ What this does:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Creates a new <span style=\" font-family:\'Courier New\';\">#define TRAINER_NAME</span> in <span style=\" font-family:\'Courier New\';\">include/constants/opponents.h</span> </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Appends a trainer block to <span style=\" font-family:\'Courier New\';\">src/data/trainers.party</span> with a Bulbasaur (Lv. 50) </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Updates <span style=\" font-family:\'Courier New\';\">TRAINERS_COUNT</span> and <span style=\" font-family:\'Courier New\';\">MAX_TRAINERS_COUNT</span> automatically </li></ul>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">📌 Notes:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The trainer name must be unique — duplicates will be rejected </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can have up to <span style=\" font-weight:700;\">1200</span> trainers. If this limit is reached, you’ll need to increase <span style=\" font-family:\'Courier New\';\">MAX_TRAINERS_COUNT</span> manually (Its recommend to replace trainers instead of adding new ones as this puts a toll on the RAM and could make the game not run if too many new trainers are added)</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">You can edit the trainer’s party and properties later in the Trainer Editor </li></ul>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">🛠️ Tips:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use simple, clear names like <span style=\" font-family:\'Courier New\';\">Brooke</span>, <span style=\" font-family:\'Courier New\';\">Lars</span>, or <span style=\" font-family:\'Courier New\';\">Elite Four Max</span> </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">After creation, your trainer will appear in the dropdown list in the Trainer Editor </li></ul></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Trainer Name"))
        self.btnCreateTrainer.setText(_translate("MainWindow", "Make Trainer"))
        self.textProjectInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700; color:#90ee90;\">🎉 Project Folder Loaded!</span><span style=\" font-size:x-large; font-weight:700;\"> </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">You\'re ready to roll!</span><br />You\'ve selected the following folder as your <span style=\" font-family:\'Courier New\';\">pokeemerald-expansion</span> project: </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">{folder}</span> </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This tool is now fully unlocked and ready to help you <span style=\" font-weight:700;\">edit, enhance, and expand</span> your Pokémon world. 🔧🚀 </p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">✨ What you can do now: </span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">➕ <span style=\" font-weight:700;\">Create brand new trainers</span> with fully customized teams </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">✏️ <span style=\" font-weight:700;\">Edit existing trainers</span> already in your project </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🖼️ <span style=\" font-weight:700;\">Import trainer front sprites</span> (.png format) </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🚶 <span style=\" font-weight:700;\">Import overworld sprites</span> (object event graphics) </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">💾 <span style=\" font-weight:700;\">Remember:</span> changes are <span style=\" font-style:italic;\">not</span> auto-saved — hit <span style=\" font-weight:700;\">Save</span> before exiting! </li></ul>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">📊 Loaded Data: </span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Trainers:</span> {len(self.trainers)} </li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Return to the sidebar to start building your perfect Pokémon experience. Let’s make something amazing! 💡🕹️</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Class"))
        self.label_5.setText(_translate("MainWindow", "Gender"))
        self.label_4.setText(_translate("MainWindow", "Picture"))
        self.label_6.setText(_translate("MainWindow", "Encounter Music"))
        self.checkDoubleBattle.setText(_translate("MainWindow", "Double Battle"))
        self.label.setText(_translate("MainWindow", "Trainer ID"))
        self.label_7.setText(_translate("MainWindow", "AI Flag"))
        self.label_8.setText(_translate("MainWindow", "Team SIze"))
        self.label_9.setText(_translate("MainWindow", "Trainer Item 1"))
        self.label_11.setText(_translate("MainWindow", "Trainer Item 2"))
        self.label_10.setText(_translate("MainWindow", "Trainer Item 3"))
        self.label_12.setText(_translate("MainWindow", "Mugshot"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700; color:#00bfff;\">🧠 Trainer Editor</span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This editor lets you view and edit trainers from your &quot;src/data/trainer.party&quot; file.</p>\n"
"<table border=\"0\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" cellspacing=\"2\" cellpadding=\"0\">\n"
"<tr>\n"
"<td width=\"50%\" style=\" vertical-align:top; padding-right:20;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    </p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">🛠️ What you can do:    </span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🔍 Search through all trainers        </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">📋 Edit Pokémon, nicknames, levels        </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🎨 Customize items and appearance        </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">💡 Enable advanced EV/IV and moves    </li></ul></td>\n"
"<td width=\"50%\" style=\" vertical-align:top; padding-right:20;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    </p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">💾 How it works:    </span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Changes are made directly to <span style=\" font-family:\'Courier New\';\">trainers.party</span>, which controls all trainer teams.    </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700; color:#ffa500;\">Note:</span><span style=\" color:#ffa500;\"> Nothing is saved until you click </span><span style=\" font-weight:700; color:#ffa500;\">Save</span><span style=\" color:#ffa500;\">. Try things out freely!</span></p></td></tr></table></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">Event Script Editor</span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use this tool to quickly generate Poryscript event code for your <span style=\" font-family:\'Courier New\';\">pokeemerald-expansion</span> project. The tool supports several common script types and automatically creates unique IDs based on map and input.</p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">✅ Supported script types for now:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Trainer Battle</span> – Creates a <span style=\" font-family:\'Courier New\';\">trainerbattle_single</span> script with intro, defeat and post-battle text. (Can make double battles like this as well if trainer is set to do double battle in the trainer editor. Will fix it to make it double in the script as well later on)</li>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\"><br /></p>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Dialog</span> – Creates a simple <span style=\" font-family:\'Courier New\';\">msgbox</span>-based script.</li>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px;\"><br /></p>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">Starter Choice</span> – Generates a script that allows picking one of three Pokémon, with flags and removal.</li></ul>\n"
"<h3 style=\" margin-top:14px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">⚙️ What happens when you click &quot;Generate&quot;:</span></h3>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A script ID is generated using map name and input prefix (e.g. Route101).</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A complete Poryscript block is generated and shown in the right-side output area.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The script is also saved to <span style=\" font-family:\'Courier New\';\">generated_scripts.txt</span> for reference.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The script is automatically written in to scripts.pory for the choosen map and are ready to be used in PoryMap.</li></ol>\n"
"<h3 style=\" margin-top:14px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">📌 Notes:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The tool reads available maps from <span style=\" font-family:\'Courier New\';\">data/maps/</span> if <span style=\" font-family:\'Courier New\';\">scripts.pory</span> exists in the folder.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Trainer IDs are pulled from <span style=\" font-family:\'Courier New\';\">include/constants/opponents.h</span>.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Species lists for starter choices can be customized via the dropdowns.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">All output appears after clicking &quot;Generate-Script&quot;</li></ul>\n"
"<h3 style=\" margin-top:14px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">📁 Output location:</span></h3>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The generated scripts are saved to:</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">generated_scripts.txt in this applications root folder.</span></p></body></html>"))
        self.importButton.setText(_translate("MainWindow", "Import Front Sprite"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">Import Trainer Front Sprites </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Use this tool to import custom trainer front sprites into your <span style=\" font-family:\'Courier New\';\">pokeemerald-expansion</span> project. You can select any number of <span style=\" font-weight:700;\">.png</span> files, and the tool will integrate them into the project. </p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">✅ What happens during import:</span></h3>\n"
"<ol style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The selected <span style=\" font-family:\'Courier New\';\">.png</span> files are copied to <span style=\" font-family:\'Courier New\';\">graphics/trainers/front_pics/</span> </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In <span style=\" font-family:\'Courier New\';\">include/constants/trainers.h</span>: \n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A new <span style=\" font-family:\'Courier New\';\">#define TRAINER_PIC_NAME</span> line is added above <span style=\" font-family:\'Courier New\';\">TRAINER_PIC_COUNT</span> </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">TRAINER_PIC_COUNT</span> is increased by 1 </li></ul></li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In <span style=\" font-family:\'Courier New\';\">src/data/graphics/trainers.h</span>: \n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 2;\">\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A <span style=\" font-family:\'Courier New\';\">gTrainerFrontPic_NAME[]</span> entry is added using <span style=\" font-family:\'Courier New\';\">.4bpp.lz</span> from your PNG </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A <span style=\" font-family:\'Courier New\';\">gTrainerPalette_NAME[]</span> entry is added for the palette (.gbapal) </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A <span style=\" font-family:\'Courier New\';\">TRAINER_SPRITE()</span> line is added to the sprite table </li></ul></li></ol>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">⚠️ Notes:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The PNG files <span style=\" font-style:italic;\">must</span> be prepared for GBA use: correct size (64×64), indexed color, and limited palette.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The tool does not convert or compress the PNG. This is all handled by pokeemerald-expansion.</li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">File names should be descriptive and consistent (e.g. <span style=\" font-family:\'Courier New\';\">ace_trainer_m</span>, <span style=\" font-family:\'Courier New\';\">cooltrainer_f</span>) </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If a sprite is already defined in the project, it will not be duplicated. </li></ul>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">📘 Resources:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"https://www.pokecommunity.com/threads/inserting-custom-sprites.416167/\"><span style=\" text-decoration: underline; color:#0000ff;\">Custom Sprite Insertion Guide</span></a> </li></ul></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<h2 style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:x-large; font-weight:700;\">Import Overworld Trainer Sprites </span></h2>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700; color:#ff0000;\">⚠️ Palettes are not fully supported yet. It\'s recommended to wait until palette functionality is properly implemented before using this tool. However the rom does build and the sprite shows in game just with wrong colors.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This tool adds overworld (object event) sprites to your <span style=\" font-family:\'Courier New\';\">pokeemerald-expansion</span> project. </p>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">✅ What this updates:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">graphics/object_events/pics/people/</span> — adds PNGs </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">include/constants/event_objects.h</span> — adds <span style=\" font-family:\'Courier New\';\">#define OBJ_EVENT_GFX_*</span> above <span style=\" font-family:\'Courier New\';\">NUM_OBJ_EVENT_GFX</span> </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">object_event_graphics_info_pointers.h</span> — adds extern + pointer reference </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">object_event_graphics.h</span> — adds <span style=\" font-family:\'Courier New\';\">gObjectEventPic_NAME</span> </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">object_event_graphics_info.h</span> — adds <span style=\" font-family:\'Courier New\';\">gObjectEventGraphicsInfo_NAME</span> struct </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">object_event_pic_tables.h</span> — adds <span style=\" font-family:\'Courier New\';\">sPicTable_NAME</span> </li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Courier New\';\">spritesheet_rules.mk</span> — adds rule for PNG-to-4bpp conversion with <span style=\" font-family:\'Courier New\';\">-mwidth 2 -mheight 4</span> </li></ul>\n"
"<h3 style=\" margin-top:14px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:large; font-weight:700;\">📌 Notes:</span></h3>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\">\n"
"<li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PNG size should be 48x32 (3 frames) or 144x32 (9 frames) </li>\n"
"<li style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Only raw PNGs are copied — you must ensure corresponding .4bpp and .gbapal files are compiled properly </li></ul></body></html>"))
        self.importButton_OW.setText(_translate("MainWindow", "Import OW Sprite"))
        self.lblFolderPath.setText(_translate("MainWindow", "No folder choosen"))
        self.menuTrainer_Editor.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionTrainerEditor.setText(_translate("MainWindow", "Trainer Editor"))
        self.actionImportTrainerPics.setText(_translate("MainWindow", "Import Trainer Front Sprite"))
        self.actionImportOverworldSprites.setText(_translate("MainWindow", "Import Trainer Overworld Sprite"))
        self.actionMapScriptEditor_2.setText(_translate("MainWindow", "Event Script Maker"))
        self.actionGithub.setText(_translate("MainWindow", "Github"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionRecent.setText(_translate("MainWindow", "Recent"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionactionOpenProjectFolder.setText(_translate("MainWindow", "actionOpenProjectFolder"))
        self.actionOpenProjectFolder.setText(_translate("MainWindow", "Open Project Folder"))
        self.actionOption1.setText(_translate("MainWindow", "Option1"))
        self.actionOption2.setText(_translate("MainWindow", "Option2"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionRecentProjectss.setText(_translate("MainWindow", "Open Recent Projects"))
        self.actionNewTrainerPage.setText(_translate("MainWindow", "Add New Trainer"))
        self.actionReloadProjectFolder.setText(_translate("MainWindow", "Reload Current Project"))
